// This file is generated by scripts/generate-env.mjs - do not edit by hand.
// It's regenerated from environment variables (or .env locally) before
// every build/serve. See .env.example for the variables it reads.
export const API_BASE_URL = 'http://localhost:8080/api';
export const WS_BASE_URL = 'ws://localhost:8080';
