import { config } from "dotenv";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

// Loads .env into process.env for local dev. On Vercel/Render the platform
// already injects real environment variables before the build runs, so
// this is a harmless no-op there if no .env file exists.
config();

const __dirname = dirname(fileURLToPath(import.meta.url));

const apiBaseUrl = process.env.API_BASE_URL ?? "http://localhost:8080/api";
const wsBaseUrl = process.env.WS_BASE_URL ?? "ws://localhost:8080";

const outPath = resolve(__dirname, "../src/app/core/config.ts");

const contents = `// This file is generated by scripts/generate-env.mjs - do not edit by hand.
// It's regenerated from environment variables (or .env locally) before
// every build/serve. See .env.example for the variables it reads.
export const API_BASE_URL = '${apiBaseUrl}';
export const WS_BASE_URL = '${wsBaseUrl}';
`;

writeFileSync(outPath, contents);
console.log(`[generate-env] wrote ${outPath}`);
console.log(`[generate-env]   API_BASE_URL = ${apiBaseUrl}`);
console.log(`[generate-env]   WS_BASE_URL  = ${wsBaseUrl}`);
