import { config } from "dotenv";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));

// 1. Explicitly point dotenv to your project root folder
config({ path: resolve(__dirname, "../.env") });

const apiBaseUrl = process.env.API_BASE_URL;
const wsBaseUrl = process.env.WS_BASE_URL;

// 2. Crash the build early if secrets are completely missing
if (!apiBaseUrl || !wsBaseUrl) {
  console.error(
    "❌ [generate-env] Error: API_BASE_URL or WS_BASE_URL is missing!",
  );
  console.error("👉 Locally: Check your .env file in the project root.");
  console.error("👉 Vercel/Render: Check your platform environment variables.");
  process.exit(1);
}

const outPath = resolve(__dirname, "../src/app/core/config.ts");

const contents = `// This file is generated by scripts/generate-env.mjs - do not edit by hand.
export const API_BASE_URL = '${apiBaseUrl}';
export const WS_BASE_URL = '${wsBaseUrl}';
`;

writeFileSync(outPath, contents);
console.log(`\n✅ [generate-env] Successfully generated ${outPath}`);
